name: Deploy FastAPI App via Self-Hosted Runner

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted  # Self-hosted GitHub runner  
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          echo "Building latest Docker image..."
          echo $SUDO_PASSWORD | sudo -S docker build -t qxresearch-event-1-image .
        env:
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}  # Securely store the sudo password in GitHub secrets

      - name: Stop & Remove Existing Container
        run: |
          CONTAINER_ID=$(sudo docker ps -aq --filter "name=qxresearch-event-1-container")
          if [ ! -z "$CONTAINER_ID" ]; then
            echo $SUDO_PASSWORD | sudo -S docker stop qxresearch-event-1-container
            echo $SUDO_PASSWORD | sudo -S docker rm qxresearch-event-1-container
          fi
          
      - name: Run New Container from Latest Image
        run: |
          echo "Running container from latest image..."
          echo $SUDO_PASSWORD | sudo -S docker run -d --name qxresearch-event-1-container -p 8000:8000 qxresearch-event-1-image

      - name: Cleanup Unused Docker Images
        run: |
          echo "Cleaning up old Docker images..."
          echo $SUDO_PASSWORD | sudo -S docker image prune -af

  sonarQube:
    runs-on: self-hosted
    needs: deploy
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SonarQube Scan
        run: |
          echo "Running SonarQube analysis..."
          echo $SUDO_PASSWORD | sudo -S docker run --rm \
            -e SONAR_HOST_URL="http://localhost:9000" \
            -e SONAR_LOGIN=$SONAR_TOKEN \
            -v $(pwd):/usr/src \
            sonarsource/sonar-scanner-cli
        env:
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}  # Securely store the sudo password in GitHub secrets

      - name: Generate PDF Report
        run: |
          echo "Generating PDF report..."
          curl -u $SONAR_LOGIN:$SONAR_TOKEN \
          "http://localhost:9000/api/qualitygates/project_status?projectKey=free" \
          -o report.json
          
          # Convert JSON to PDF (use a tool or custom script)
          python3 generate_pdf_report.py report.json

  nginx:
    runs-on: self-hosted
    needs: deploy
    
    steps:
      - name: Test and Reload Nginx
        run: |
          echo "Testing nginx configuration..."
          echo $SUDO_PASSWORD | sudo -S nginx -t && sudo systemctl restart nginx
        env:
          SUDO_PASSWORD: ${{ secrets.SUDO_PASSWORD }}  # Securely store the sudo password in GitHub secrets
